### ISSUE TITLE
Hexes compared with ncurses, urwid, etc?

### ISSUE THREAD

**Issue by prologic** [wlonk/hexes#1]
What do you intend to make different about hexes to set it apart from other _curses libraries and frameworks? (_you only have stubs right now in the codebase*).

**Comment by wlonk** [comment]
I can't give a better answer yet than simply that those projects don't quite sit right with me; they feel like they add a lot of boilerplate and don't work well with how I want to write a curses-based UI. I'm not sure if I can do better yet, but I've been possessed by the desire to try!

Thanks for the question; I only made this repo an hour or two ago, so I'm surprised to find an issue already opened!

**Comment by prologic** [comment]
No problems :) I'll keep en eye out on what idea you come up :)

Don't be surprised! I watch my PyPi feeds carefully :)
